name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter Codigo"
      - run: echo "Executar o Docker Builder"
      - run: echo "Enviar a Imagem Docker para Docker Hub"

  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter Codigo"
      - run: echo "Configurar o Kubeconfig"
      - run: echo "Executar o apply"


      

      
      
    
